<?php
return [
    'db_table' => [
        'TBL_CUSTOMERS' => 'customers',
        'TBL_ADMINS' => 'admins',
        'TBL_CATEGORIES' => 'categories',
        'TBL_PRODUCTS' => 'products',
        'TBL_VOUCHERS' => 'vouchers',
        'TBL_BRANDS' => 'brands',
        'TBL_ATTRIBUTES' => 'attributes',
        'TBL_PRODUCT_ATTRIBUTE' => 'product_attribute',
        'TBL_PRODUCT_IMAGES' => 'product_images',
        'TBL_REPOSITORIES' => 'repositories',
        'TBL_ORDER_VOUCHER' => 'order_voucher',
        'TBL_PRODUCT_REPOSITORY' => 'product_repository',
        'TBL_PRODUCT_REVIEWS' => 'product_reviews',
        'TBL_PRODUCT_REVIEW_IMAGES' => 'product_review_images',
        'TBL_CUSTOMER_PRODUCT' => 'customer_product',
        'TBL_ADDRESSES' => 'addresses',
        'TBL_ORDERS' => 'orders',
        'TBL_ORDER_PRODUCT' => 'order_product',
        'TBL_PROVINCES' => 'provinces',
        'TBL_DISTRICTS' => 'districts',
        'TBL_WARDS' => 'wards',
        'TBL_PAYMENTS' => 'payments',
        'TBL_SHIPPED' => 'shipped',
    ],
    'TOKEN' => 'daylatokenbimat',
];
